services:
  redcarpet:
    build: .
    env_file:
      - application.env
    ports:
      - "8080:8080"
    depends_on:
      redcarpet-db:
        condition: service_healthy

  redcarpet-db:
    image: postgres:15-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: redcarpet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: redcarpet
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s